declare const _Number: NumberConstructor;
declare const _Boolean: BooleanConstructor;
declare const _String: StringConstructor;
declare const _Symbol: SymbolConstructor;
declare const _Object: ObjectConstructor;
declare const _Array: ArrayConstructor;
declare const _Set: SetConstructor;
declare const _Map: MapConstructor;
declare const _Math: Math;
export { _Number, _Boolean, _String, _Symbol, _Object, _Array, _Set, _Map, _Math };
