import { isInstanceOf } from "./is/instanceOf";
import { isPromise } from "./is/promise";
import { isTypeOf } from "./is/typeOf";
import { getName } from "./get/name";
import { numClamp } from "./num/clamp";
import { numSafe } from "./num/safe";
import { strDistance } from "./str/distance";
import { strSimilar } from "./str/similar";
import { strToPascalCase } from "./str/toPascalCase";
import { arrCollect } from "./arr/collect";
import { arrCount } from "./arr/count";
import { arrRemoveIndex } from "./arr/removeIndex";
import { arrRemoveItem } from "./arr/removeItem";
import { arrStep } from "./arr/step";
import { objDecycle } from "./obj/decycle";
import { searchBinary } from "./search/binary";
export { isInstanceOf, isTypeOf, isPromise, getName, numClamp, numSafe, strDistance, strSimilar, strToPascalCase, arrStep, arrRemoveIndex, arrRemoveItem, arrCount, arrCollect, objDecycle, searchBinary };
